env: product-dev

spring:
  application:
    name: product
  datasource:
    username: root
    password: shen123
    url: jdbc:mysql:///pm111
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.0.111
    username: guest
    password: guest
    port: 5672
server:
  port: 8083
