spring:
  datasource:
    username: root
    password: shen123
    url: jdbc:mysql://pm111
  redis:
    host: 192.168.0.103
    port: 6379
  rabbitmq:
    host: 192.168.0.103
    username: guest
    password: guest
    port: 5672

server:
  port: 9090
