spring:
  datasource:
    username: root
    password: shen123
    url: jdbc:mysql:///pm111
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.0.110
    port: 6379
  rabbitmq:
    host: 192.168.0.110
    username: guest
    password: guest
    port: 5672

server:
  port: 9090
